version: "3.8"
services:
    app:
        image: php:8.2-fpm
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - db

    web:
        image: nginx:alpine
        container_name: nginx_web
        volumes:
            - .:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8080:80"
        networks:
            - app-network
        depends_on:
            - app

    db:
        image: mysql:5.7
        container_name: mysql_db
        environment:
            MYSQL_DATABASE: elmensual
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
